#!/bin/bash

# Check if Bluetooth is enabled
if bluetoothctl show | grep -q "Powered: yes"; then
    connected_devices=$(bluetoothctl devices Connected | awk '{print $3}')
    
    if [ -n "$connected_devices" ]; then
        echo " ${connected_devices//$'\n'/, }"
    else
        echo " Bluetooth"
    fi
else
    echo " Off"
fi

# Click handling
case $BLOCK_BUTTON in
    1) blueman-manager ;;  # Left click
esac
