#!/bin/bash

# Requires rofi
options="Lock\nLogout\nReboot\nShutdown\nSuspend\nHibernate"
chosen=$(echo -e "$options" | rofi -dmenu -p "Power Menu:")

case "$chosen" in
    Lock) i3lock ;;
    Logout) i3-msg exit ;;
    Reboot) systemctl reboot ;;
    Shutdown) systemctl poweroff ;;
    Suspend) systemctl suspend ;;
    Hibernate) systemctl hibernate ;;
esac
