[general]
import = [
    "~/.config/alacritty/themes/themes/aafterglow.toml"
]

[window]
opacity = 0.7
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Dark" # or "Light"

[font]
size = 9.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[keyboard]
bindings = [
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
